apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: kafka-port
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: kafka
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: kafka
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: kafka
data:
  init.sh: |
    #!/bin/bash
    set -ex
    # More thorough cleanup
    rm -rf /data/kafka/meta.properties
    rm -rf /data/kafka/__consumer_offsets-*
    rm -rf /data/kafka/cleaner-offset-checkpoint
    rm -rf /data/kafka/recovery-point-offset-checkpoint
    rm -rf /data/kafka/log-start-offset-checkpoint
    rm -rf /data/kafka/replication-offset-checkpoint
    mkdir -p /data/kafka
    chown -R 1000:1000 /data/kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
  labels:
    app: kafka
spec:
  serviceName: kafka-headless
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
      - name: init-config
        image: busybox
        command: ['/bin/sh', '-c', 'sh /config-map/init.sh']
        volumeMounts:
        - name: config-map
          mountPath: /config-map
        - name: data
          mountPath: /data
      containers:
      - name: kafka
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
          name: kafka
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service:2181
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-service:9092
        - name: HOSTNAME_COMMAND
          value: "hostname -f"
        - name: KAFKA_LOG_DIRS
          value: "/data/kafka"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_NUM_PARTITIONS
          value: "1"
        - name: KAFKA_LOG_RETENTION_HOURS
          value: "168"
        - name: JMX_PORT
          value: "9999"
        - name: KAFKA_DELETE_TOPIC_ENABLE
          value: "true"
        - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
          value: "60000"
        - name: KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS
          value: "60000"
        - name: KAFKA_CONTROLLED_SHUTDOWN_ENABLE
          value: "true"
        - name: KAFKA_AUTO_LEADER_REBALANCE_ENABLE
          value: "true"
        - name: KAFKA_RESTART_ATTEMPTS
          value: "10"
        - name: KAFKA_RESTART_DELAY_MS
          value: "5000"
        volumeMounts:
        - name: data
          mountPath: /data
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 6
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 60
          timeoutSeconds: 10
          periodSeconds: 20
          failureThreshold: 6
        lifecycle:
          postStart:
            exec:
              command:
              - "sh"
              - "-c"
              - "sleep 10 && kafka-topics.sh --create --if-not-exists --zookeeper zookeeper-service:2181 --partitions 1 --replication-factor 1 --topic __consumer_offsets || true"
        resources:  
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "300m"
      volumes:
      - name: config-map
        configMap:
          name: kafka-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi