apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-sender
  namespace: kafka
  labels:
    app: request-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-sender
  template:
    metadata:
      labels:
        app: request-sender
    spec:
      containers:
      - name: request-sender
        image: request-sender:latest  
        imagePullPolicy: IfNotPresent