apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-mesh-admin-role
rules:
- apiGroups: ["chaos-mesh.org"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods", "namespaces", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-mesh-admin-binding
subjects:
- kind: ServiceAccount
  name: chaos-mesh-admin
  namespace: chaos-mesh
roleRef:
  kind: ClusterRole
  name: chaos-mesh-admin-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-mesh-controller-admin-binding
subjects:
- kind: ServiceAccount
  name: chaos-controller-manager
  namespace: chaos-mesh
roleRef:
  kind: ClusterRole
  name: chaos-mesh-admin-role
  apiGroup: rbac.authorization.k8s.io