apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
  namespace: kafka
type: Opaque
data:
  mongo-username: MjI1MjA5ODg= # base64 của "22520988"
  mongo-password: MjI1MjA5ODg= # base64 của "22520988"